version: "1"

services:
  jupyter:
    image: quay.io/jupyter/minimal-notebook
    container_name: panoseti_data_labeling
    volumes:
      - .:/home/jovyan/work
      - ./configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    ports:
      - 8888:8888
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=nbclassic
    working_dir: /home/jovyan/work/
